#!/bin/bash

LIB_PATH="${lib-path}"

if [ ! -d "$LIB_PATH" ]; then
  # Control will enter here if $DIRECTORY exists.


SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

LIB_PATH="$DIR/../lib"

fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

CP="."
for f in $(find "$LIB_PATH" -iname "*.jar"); do
  CP="$CP:$f"
done
IFS=$SAVEIFS

java -classpath "$CP" be.dns.rdap.client.RDAPCLI $@